create modal component, styles
mialav24/ToDo pull request #4
Opened 2023-12-18 20:22 UTC by mialav24

![modal-component](https://github.com/mialav24/ToDo/assets/67606930/27ab6858-e13f-4845-9aae-c1a90bd69f23)

2023-12-18 22:15 UTC, jlmonroy13 requested changes

2023-12-18 22:15 UTC, jlmonroy13 commented on src/Components/App/App.tsx
> +            disabled={categoryTitle.length >= 3 ? false : true}
would be better to write this in this way

`disabled={!(categoryTitle.length >= 3)}`

2023-12-18 22:15 UTC, jlmonroy13 commented on src/Components/Modal/Modal.styles.ts
> +  min-height: 0;
Do we need this?

2023-12-18 22:15 UTC, jlmonroy13 commented on src/Components/Modal/Modal.tsx
> +  categories: { id: string; title: string }[] | [];
Create a type called `Category` and use it here

`cateagories: Category[] | []`

2023-12-18 22:15 UTC, jlmonroy13 commented on src/Components/Modal/Modal.tsx
> +        <TextArea placeholder="Type your task..." name="" id=""></TextArea>
TextArea doesn't need a close tag

2023-12-18 22:15 UTC, jlmonroy13 commented on src/Components/Modal/Modal.tsx
> +          <select id="">
what is this id for?

2023-12-19 14:31 UTC, mialav24 commented on src/Components/App/App.tsx
> +            disabled={categoryTitle.length >= 3 ? false : true}
ok, SAPO HPTA!.

2023-12-19 15:08 UTC, mialav24 commented on src/Components/Modal/Modal.styles.ts
> +  min-height: 0;
you're right, deleted lines 22 and 23, just needed 20 and 21.

2023-12-19 15:08 UTC, mialav24 commented on src/Components/Modal/Modal.tsx
> +        <TextArea placeholder="Type your task..." name="" id=""></TextArea>
ok

2023-12-19 18:55 UTC, jlmonroy13 approved these changes

2023-12-19 19:07 UTC, merged